# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve [--baseurl '']'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Gulp Boilerplate
email: esausilva85@gmail.com
description: A boilerplate project including full setup for Jekyll, GulpJS, SASS, PostCSS, BrowserSync, Autoprefixer and deploy to GitHub Pages using Gulp.
baseurl: '/jekyll-gulp-boilerplate' # the subpath of your site, e.g. /blog
url: 'http://esausilva.github.io/jekyll-gulp-boilerplate' # the base hostname & protocol for your site, e.g. http://example.com or http://[yourusername].github.io/[project]

# Build settings
markdown: kramdown
exclude: ['node_modules', 'gulpfile.js', 'package.json']
plugins:
  - jekyll-minifier
jekyll-minifier:
  exclude: ['assets/css/*.css', '*.min.*']
